
const IMAGES = [
    require("./A.png"),
    require("./2.png"),
    require("./3.png"),
    require("./4.png"),
    require("./5.png"),
    require("./6.png"),
    require("./7.png"),
    require("./8.png"),
    require("./9.png"),
    require("./10.png"),
    require("./J.png"),
    require("./Q.png"),
    require("./K.png"),
    require("./A-2.png"),
    require("./2-2.png"),
    require("./3-2.png"),
    require("./4-2.png"),
    require("./5-2.png"),
    require("./6-2.png"),
    require("./7-2.png"),
    require("./8-2.png"),
    require("./9-2.png"),
    require("./10-2.png"),
    require("./J-2.png"),
    require("./Q-2.png"),
    require("./K-2.png"),
    require("./Joker_2.png"),
    require("./A-3.png"),
    require("./2-3.png"),
    require("./3-3.png"),
    require("./4-3.png"),
    require("./5-3.png"),
    require("./6-3.png"),
    require("./7-3.png"),
    require("./8-3.png"),
    require("./9-3.png"),
    require("./10-3.png"),
    require("./J-3.png"),
    require("./Q-3.png"),
    require("./K-3.png"),
    require("./A-1.png"),
    require("./2-1.png"),
    require("./3-1.png"),
    require("./4-1.png"),
    require("./5-1.png"),
    require("./6-1.png"),
    require("./7-1.png"),
    require("./8-1.png"),
    require("./9-1.png"),
    require("./10-1.png"),
    require("./J-1.png"),
    require("./Q-1.png"),
    require("./K-1.png"),
    require("./Joker_1.png"),
    require("./Card_Back.png")
]
// const IMAGES = {
//     clubA:      require("./A_club.svg"),
//     club2:      require("./2_club.svg"),
//     club3:      require("./3_club.svg"),
//     club4:      require("./4_club.svg"),
//     club5:      require("./5_club.svg"),
//     club6:      require("./6_club.svg"),
//     club7:      require("./7_club.svg"),
//     club8:      require("./8_club.svg"),
//     club9:      require("./9_club.svg"),
//     club10:     require("./10_club.svg"),
//     clubJ:      require("./J_club.svg"),
//     clubQ:      require("./Q_club.svg"),
//     clubK:      require("./K_club.svg"),
//     heartA:     require("./A_heart.svg"),
//     heart2:     require("./2_heart.svg"),
//     heart3:     require("./3_heart.svg"),
//     heart4:     require("./4_heart.svg"),
//     heart5:     require("./5_heart.svg"),
//     heart6:     require("./6_heart.svg"),
//     heart7:     require("./7_heart.svg"),
//     heart8:     require("./8_heart.svg"),
//     heart9:     require("./9_heart.svg"),
//     heart0:     require("./10_heart.svg"),
//     heartJ:     require("./J_heart.svg"),
//     heartQ:     require("./Q_heart.svg"),
//     heartK:     require("./K_heart.svg"),
//     jokerRed:   require("./Joker_red.svg"),
//     spadeA:     require("./A_spade.svg"),
//     spade2:     require("./2_spade.svg"),
//     spade3:     require("./3_spade.svg"),
//     spade4:     require("./4_spade.svg"),
//     spade5:     require("./5_spade.svg"),
//     spade6:     require("./6_spade.svg"),
//     spade7:     require("./7_spade.svg"),
//     spade8:     require("./8_spade.svg"),
//     spade9:     require("./9_spade.svg"),
//     spade10:    require("./10_spade.svg"),
//     spadeJ:     require("./J_spade.svg"),
//     spadeQ:     require("./Q_spade.svg"),
//     spadeK:     require("./K_spade.svg"),
//     diamondA:   require("./A_diamond.svg"),
//     diamond2:   require("./2_diamond.svg"),
//     diamond3:   require("./3_diamond.svg"),
//     diamond4:   require("./4_diamond.svg"),
//     diamond5:   require("./5_diamond.svg"),
//     diamond6:   require("./6_diamond.svg"),
//     diamond7:   require("./7_diamond.svg"),
//     diamond8:   require("./8_diamond.svg"),
//     diamond9:   require("./9_diamond.svg"),
//     diamond10:  require("./10_diamond.svg"),
//     diamondJ:   require("./J_diamond.svg"),
//     diamondQ:   require("./Q_diamond.svg"),
//     diamondK:   require("./K_diamond.svg"),
//     jokeBlack:  require("./Joker_black.svg")
// }


export default IMAGES